/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Cliente;
import Clases.Empleado;
import Clases.Espectaculo;
import Clases.MetaData;
import Clases.MetaDataColumn;
import Clases.MetaDataTable;
import juan_parquestematicos.Main;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author iBaD
 */
public class VMetaData extends javax.swing.JFrame {
    
    private MetaData metaData;
    private MetaDataTable tablaSelected;
    
    public VMetaData() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public VMetaData(MetaData meta){
        initComponents();
        setLocationRelativeTo(null);
        this.metaData = meta;
        RellenarMetaDatos();
        RellenarComboTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbTabla = new javax.swing.JComboBox<>();
        eNombre = new javax.swing.JLabel();
        tUrl = new javax.swing.JTextField();
        eNombre1 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tColumnas = new javax.swing.JTextArea();
        eNombre2 = new javax.swing.JLabel();
        tDriver = new javax.swing.JTextField();
        eNombre3 = new javax.swing.JLabel();
        tCliente = new javax.swing.JTextField();
        tEsquema = new javax.swing.JTextField();
        eNombre4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MetaDatos de la BD");

        btCerrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btCerrar.setText("Cerrar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tabla:");

        cbTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTablaActionPerformed(evt);
            }
        });

        eNombre.setText("URL:");

        tUrl.setEditable(false);

        eNombre1.setText("Nombre:");

        tNombre.setEditable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Columnas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tColumnas.setEditable(false);
        tColumnas.setColumns(20);
        tColumnas.setRows(5);
        jScrollPane1.setViewportView(tColumnas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        eNombre2.setText("Driver:");

        tDriver.setEditable(false);

        eNombre3.setText("Cliente:");

        tCliente.setEditable(false);

        tEsquema.setEditable(false);

        eNombre4.setText("Esquema:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eNombre)
                            .addComponent(eNombre1)
                            .addComponent(eNombre2)
                            .addComponent(eNombre3)
                            .addComponent(jLabel2)
                            .addComponent(eNombre4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tUrl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tNombre)
                            .addComponent(tDriver)
                            .addComponent(tCliente)
                            .addComponent(cbTabla, 0, 300, Short.MAX_VALUE)
                            .addComponent(tEsquema))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNombre1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombre)
                    .addComponent(tUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombre2)
                    .addComponent(tDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombre3)
                    .addComponent(tCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNombre4)
                    .addComponent(tEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCerrar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        Main.cerrarVentanaMetaDatos();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void cbTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTablaActionPerformed
        int index = cbTabla.getSelectedIndex()-1;
        MetaDataTable tabla = null;
        if(index > -1){
            tabla = this.metaData.getListaTablas().get(index);
        }
        if(tabla == null){
            LimpiarCampos();
        }else{
            this.tablaSelected = tabla;
            AutocompletarDatosTabla();
        }
    }//GEN-LAST:event_cbTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMetaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMetaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMetaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMetaData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMetaData().setVisible(true);
            }
        });
    }
    
    public void RellenarMetaDatos(){
        tNombre.setText(this.metaData.getNombreBD());
        tDriver.setText(this.metaData.getDriverBD());
        tUrl.setText(this.metaData.getUrlDB());
        tCliente.setText(this.metaData.getClienteDB());
    }
    
    public void LimpiarCampos(){
        tEsquema.setText("");
        tColumnas.setText("");
    }
    
     public void AutocompletarDatosTabla(){
        tEsquema.setText(this.tablaSelected.getEsquema());
        StringBuilder textoColumnas = new StringBuilder();
        if(!this.tablaSelected.getListaColumnas().isEmpty()){
            textoColumnas.append("Columnas de la tabla "+this.tablaSelected.getNombre()+":\n\n");
            for(MetaDataColumn columna : this.tablaSelected.getListaColumnas()){
                textoColumnas.append(columna.toString()+"\n");
            }
        }else{
            textoColumnas.append("Ha ocurrido un problema al cargar las columnas de la tabla o la tabla está vacía.");
        }
        tColumnas.setText(textoColumnas.toString());
    }
     
     public void RellenarComboTablas(){
        cbTabla.removeAllItems();
        if(!this.metaData.getListaTablas().isEmpty()){
             cbTabla.addItem("-----Elegir tabla-----");
            try{
                for(MetaDataTable tabla : this.metaData.getListaTablas()){
                    cbTabla.addItem(tabla.getNombre());
                }
            }catch(Exception e){
                System.out.println("ha ocurrido un error "+ e.getMessage());
            } 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private javax.swing.JComboBox<String> cbTabla;
    private javax.swing.JLabel eNombre;
    private javax.swing.JLabel eNombre1;
    private javax.swing.JLabel eNombre2;
    private javax.swing.JLabel eNombre3;
    private javax.swing.JLabel eNombre4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCliente;
    private javax.swing.JTextArea tColumnas;
    private javax.swing.JTextField tDriver;
    private javax.swing.JTextField tEsquema;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tUrl;
    // End of variables declaration//GEN-END:variables
}
