USE AD_PARQUES_TEMATICOS;

CREATE TABLE PARQUE( 
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL, 
FECHA_APERTURA DATE NOT NULL, 
DIRECCION VARCHAR(100) NOT NULL 
);

INSERT INTO PARQUE VALUES(null,'Warner',SYSDATE(),'Direccion de prueba para la Warner' );

CREATE TABLE EMPLEADOS(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
FECHA_CONTRATO DATE NOT NULL,
NACIONALIDAD VARCHAR(50) NOT NULL,
CARGO VARCHAR(50) NOT NULL,
BAJA BOOLEAN DEFAULT 0
);

CREATE TABLE ESPECTACULOS(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
AFORO INTEGER DEFAULT 0,
DESCRIPCION VARCHAR(150),
LUGAR VARCHAR(50) NOT NULL,
BAJA BOOLEAN DEFAULT 0,
EMPLEADO_FK INTEGER,
FOREIGN KEY (EMPLEADO_FK) REFERENCES EMPLEADOS(ID)
);

CREATE TABLE CLIENTES(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
BAJA BOOLEAN DEFAULT 0
);

CREATE TABLE ESPECTACULO_CLIENTE(
ID_ESPECTACULO INTEGER NOT NULL,
ID_CLIENTE INTEGER NOT NULL,
PRIMARY KEY (ID_ESPECTACULO,ID_CLIENTE),
FOREIGN KEY (ID_ESPECTACULO) REFERENCES ESPECTACULOS(ID),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);