CREATE TABLE CLIENTES( 
    DNI VARCHAR(15) PRIMARY KEY, 
    NOMBRE VARCHAR(50) NOT NULL, 
    APELLIDO VARCHAR(50) NOT NULL, 
    FECHA_NACIMIENTO DATE NOT NULL, 
    BAJA BOOLEAN DEFAULT 0 
);

CREATE TABLE EMPLE( 
    DNI VARCHAR(15) PRIMARY KEY, 
    NOMBRE VARCHAR(50) NOT NULL, 
    APELLIDO VARCHAR(50) NOT NULL, 
    FECHA_NACIMIENTO DATE NOT NULL, 
    FECHA_CONTRATO DATE NOT NULL, 
    NACIONALIDAD VARCHAR(50) NOT NULL, 
    CARGO VARCHAR(50) NOT NULL, 
    BAJA BOOLEAN DEFAULT 0 
);

CREATE TABLE PARQUE( 
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    NOMBRE VARCHAR(50) NOT NULL, 
    FECHA_APERTURA DATE NOT NULL, 
    DIRECCION VARCHAR(100) NOT NULL 
);

CREATE TABLE ESPECTACULOS( 
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    NOMBRE VARCHAR(50) NOT NULL, 
    AFORO INTEGER DEFAULT 0, 
    DESCRIPCION VARCHAR(150), 
    LUGAR VARCHAR(50) NOT NULL, 
    BAJA BOOLEAN DEFAULT 0, 
    EMPLEADO_FK VARCHAR(15), 
    FOREIGN KEY (EMPLEADO_FK) REFERENCES EMPLE(DNI) 
);

CREATE TABLE ESPECTACULO_CLIENTE( 
    ID_ESPECTACULO INTEGER NOT NULL, 
    DNI_CLIENTE INTEGER NOT NULL, 
    FOREIGN KEY (ID_ESPECTACULO) REFERENCES ESPECTACULOS(ID), 
    FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI), 
    PRIMARY KEY (ID_ESPECTACULO,DNI_CLIENTE) 
);